apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  labels:
    app: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: ghcr.io/EvgheniAlexeev/identity-service:v1.0.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "k8s"
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: identity-service-secrets
                  key: keycloak-auth-server-url
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  name: identity-service-secrets
                  key: keycloak-realm
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: identity-service-secrets
                  key: keycloak-client-id
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: identity-service-secrets
                  key: keycloak-client-secret
            - name: POSTGRES_HOST
              value: "postgresql"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: identity-service-secrets
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: identity-service-secrets
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: identity-service-secrets
                  key: postgres-password
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
