apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secrets
  labels:
    app: identity-service
type: Opaque
stringData:
  keycloak-auth-server-url: "${KEYCLOAK_AUTH_SERVER_URL}"
  keycloak-realm: "${KEYCLOAK_REALM}"
  keycloak-client-id: "${KEYCLOAK_CLIENT_ID}"
  keycloak-client-secret: "${KEYCLOAK_CLIENT_SECRET}"
  postgres-db: "${IDENTITY_POSTGRES_DB}"
  postgres-user: "${IDENTITY_POSTGRES_USER}"
  postgres-password: "${IDENTITY_POSTGRES_PASSWORD}"
