apiVersion: v1
kind: Secret
metadata:
  name: infrastructure-secrets
  labels:
    app: infrastructure
type: Opaque
stringData:
  mongo-root-username: "${MONGO_ROOT_USERNAME}"
  mongo-root-password: "${MONGO_ROOT_PASSWORD}"
  rabbitmq-username: "${RABBITMQ_USERNAME}"
  rabbitmq-password: "${RABBITMQ_PASSWORD}"
  keycloak-admin: "${KEYCLOAK_ADMIN}"
  keycloak-admin-password: "${KEYCLOAK_ADMIN_PASSWORD}"
  keycloak-db-url: "${KEYCLOAK_DB_URL}"
  keycloak-db-username: "${KEYCLOAK_DB_USERNAME}"
  keycloak-db-password: "${KEYCLOAK_DB_PASSWORD}"
  postgres-user: "${POSTGRES_USER}"
  postgres-password: "${POSTGRES_PASSWORD}"
  postgres-db: "${POSTGRES_DB}"
  grafana-admin-user: "${GRAFANA_ADMIN_USER}"
  grafana-admin-password: "${GRAFANA_ADMIN_PASSWORD}"
