apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  labels:
    app: payment-service
type: Opaque
stringData:
  mongodb-uri: "${PAYMENT_MONGODB_URI}"
  rabbitmq-username: "${RABBITMQ_USERNAME}"
  rabbitmq-password: "${RABBITMQ_PASSWORD}"
