apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-helm-values
data:
  values.yaml: |
    auth:
      username: "${POSTGRES_USER}"
      password: "${POSTGRES_PASSWORD}"
      database: "${POSTGRES_DB}"
    primary:
      persistence:
        enabled: true
        size: 8Gi
